/**
 * WhatsApp Message Formatter
 *
 * Builds a properly structured WhatsApp Business API interactive message
 * with a CTA button linked to the deep link. This output format can be
 * sent directly via the WhatsApp Cloud API or Gupshup API.
 *
 * The text format follows standard WhatsApp Business formatting:
 * - *bold* for emphasis
 * - Line breaks for readability
 * - URL button at the bottom
 */

import type { TenantConfig } from '../config/tenant-config'

export type WhatsAppTextSection = {
  type: 'text'
  text: string
}

export type WhatsAppUrlButton = {
  type: 'url_button'
  buttonLabel: string
  url: string
}

/**
 * Structured WhatsApp message payload.
 * - `body`: The main text body of the message (WhatsApp Business API `body` field).
 * - `footer`: A small note at the bottom (optional in some providers).
 * - `button`: CTA button with a URL and label.
 * - `plainText`: A combined plain-text fallback for rendering in sandbox/logs.
 */
export type WhatsAppMessagePayload = {
  body: string
  footer: string
  button: WhatsAppUrlButton
  plainText: string
}

/**
 * Format a WhatsApp Business style message with a trackable deep link CTA button.
 *
 * @param bodyText - The main message text (generated by the LLM or playbook)
 * @param deepLink - The fully resolved deep link URL for this specific user
 * @param config - (optional) override the default tenant config
 */
export const buildWhatsAppMessage = (
  bodyText: string,
  deepLink: string,
  config: TenantConfig
): WhatsAppMessagePayload => {
  const footer = 'ClickPe | Powered by NudgeFlow'

  const button: WhatsAppUrlButton = {
    type: 'url_button',
    buttonLabel: config.ctaButtonLabel,
    url: deepLink
  }

  // Plain text fallback — for sandbox view and logging
  const plainText = `${bodyText}\n\n🔗 ${button.buttonLabel}: ${deepLink}\n\n_${footer}_`

  return {
    body: bodyText,
    footer,
    button,
    plainText
  }
}
