export const MEMORY_WINDOW_MESSAGES = 20
export const MEMORY_PROMPT_MESSAGE_CAP = 16
export const MEMORY_PROMPT_CHAR_CAP = 6000
export const SUMMARY_TRIGGER_MESSAGE_COUNT = 30
export const SUMMARY_TARGET_CHAR_LIMIT = 1200
